### ISSUE TITLE
how do i get Attribute value if the object is not visible in katalon?

### ISSUE THREAD

**Issue by BBLabPawanMaurya** [katalon-studio/katalon-studio-platform#46]
println("Visibility "+WebUI.waitForElementVisible(findTestObject('Object Repository/DashbordObject/automationAssertionObject'), 30))

And I got this
Visibility false

thanks
please help me out

**Comment by zeeshanyshaikh** [comment]
can you check if the element you are trying to check is visible? Please add more details to your question.

**Comment by devalex88** [comment]
Please ask your question in forum.
